# Configuration for support-requests - https://github.com/dessant/support-requests

# Label used to mark issues as support requests
supportLabel: "type: question/stack overflow"
# Comment to post on issues marked as support requests. Add a link
# to a support page, or set to `false` to disable
supportComment: >
  We use the issue tracker exclusively for bug reports and feature requests.
  This issue appears to be a general usage or support question. 
  Instead, please ask a question on Stack Overflow with the [`detox`](https://stackoverflow.com/questions/tagged/detox) tag.
  
  Feel free to post your Stack Overflow question here for more visility. We'll take a look at it.
  
  For more information on bots in this reporsitory, read [this discussion](https://github.com/wix/Detox/issues/1305).
# Whether to close issues marked as support requests
close: true
# Whether to lock issues marked as support requests
lock: false
