#!/usr/bin/env node

const fs = require('fs');
const env = Object.keys(process.env)
  .filter(k => k.toUpperCase().startsWith('DETOX_'))
  .reduce((acc, key) => {
    acc[key] = process.env[key];
    return acc;
  }, {});

const [, ...argv] = process.argv;

const output = JSON.stringify({ env, argv }) + '\n';
if (process.env.CLI_TEST_STDOUT) {
    fs.appendFileSync(process.env.CLI_TEST_STDOUT, output);
} else {
    process.stdout.write(output);
}

if (process.env.CLI_EXIT_CODE) {
    process.exit(+process.env.CLI_EXIT_CODE);
}
