steps:
  - block: ":partyparrot: Enter the Debug Mode!"
    prompt: "Detox your mind"
    if: 'build.message =~ /^debug\$/i'
    fields:
      - select: "Ingridients"
        key: "debug-builds"
        multiple: true
        hint: "hey Chef, what are we cooking today?"
        options:
          - label: "iOS RN 70"
            value: "ios_rn_71"
          - label: "iOS RN 70"
            value: "ios_rn_71"
          - label: "iOS Demo App RN 70"
            value: "ios_demo_app_rn_70"
          - label: "iOS Demo App RN 71"
            value: "ios_demo_app_rn_71"
          - label: "Android RN 70"
            value: "android_rn_70"
          - label: "Android RN 71"
            value: "android_rn_71"
          - label: "Android Demo App RN 71"
            value: "android_demo_app_rn_71"

  - label: "Get Release Pipeline"
    command: '.buildkite/pipeline.sh debug | buildkite-agent pipeline upload'
