  - wait: ~
    continue_on_failure: true
  - label: "Post-processing: Test coverage"
    command:
      - "mkdir -p aggregated-coverage"
      - "buildkite-agent artifact download '**/*.lcov' aggregated-coverage"
      - "bash scripts/aggregate_coverage.sh"
