name: "Bug Report - iOS"
description: Create a report to help us improve Detox on iOS
labels: ["type: triage/bug", "z_platform: ios"]
body:
  - type: markdown
    attributes:
      value: Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: expected-behaviour
    attributes:
      label: What was the expected behaviour?
      description: A clear and concise description of what was expected to happen.
  - type: checkboxes
    id: tested-last-detox
    attributes:
      label: Was it tested on latest Detox?
      description: Before reporting this issue, please make sure it can be reproduced on the latest released version of Detox.
      options:
        - label: I have tested this issue on the latest Detox release and it still reproduces.
          required: true
  - type: checkboxes
    id: timeout
    attributes:
      label: Did your test throw out a timeout?
      description: If this is the case, try going over our synchronization troubleshooting guide.
      options:
        - label: I have followed the instructions under [Identifying which synchronization mechanism causes us to wait too much](https://wix.github.io/Detox/docs/troubleshooting/synchronization#identifying-which-synchronization-mechanism-causes-us-to-wait-too-much).
  - type: textarea
    id: reproduction
    attributes:
      label: Help us reproduce this issue!
      description: "Provide the steps necessary to reproduce the issue. If you are seeing a regression, try to provide the last known version where the issue did not reproduce.\n\n
      In case of a vague bug or a crash, please create an example project that reproduces it by forking the ready-to-go [DetoxTemplate project](https://github.com/wix-incubator/DetoxTemplate) and applying the minimal changes required for it to reproduce (e.g. add 3rd party libraries / E2E tests). For complete information, please review the guidelines there."
  - type: markdown
    attributes:
      value: "\n---\n## In what environment did this happen?"
  - type: input
    id: detox-version
    attributes:
      label: Detox version
    validations:
      required: true
  - type: input
    id: rn-version
    attributes:
      label: React Native version
  - type: input
    id: nodejs-version
    attributes:
      label: Node version
  - type: input
    id: device-model
    attributes:
      label: Device model
  - type: input
    id: xcode-version
    attributes:
      label: Xcode version
  - type: input
    id: ios-version
    attributes:
      label: iOS version
  - type: input
    id: macos-version
    attributes:
      label: macOS version
  - type: dropdown
    id: test-runner
    attributes:
      label: Test runner
      description: "Note: Test-runner is set in your detox configuration file (e.g. package.json, detox.config)."
      options: ["jest-circus", "jest-jasmine2 (deprecated)", "mocha", "other"]
  - type: textarea
    id: detox-logs
    attributes:
      label: Detox logs
      description: Please run your tests using the `--loglevel trace` argument. See [artifacts documentation](https://wix.github.io/Detox/docs/api/artifacts).
      value: "<details><summary>Detox logs</summary>\n\n```\npaste logs here!\n```\n\n</details>"
  - type: textarea
    id: device-logs
    attributes:
      label: Device logs
      description: Please run your tests using the `--record-logs all` argument. See [artifacts documentation](https://wix.github.io/Detox/docs/api/artifacts).
      value: "<details><summary>Device logs</summary>\n\n```\npaste logs here!\n```\n\n</details>"
  - type: textarea
    id: test-artifacts
    attributes:
      label: More data, please!
      description: Please provide any other relevant test artifacts (Screenshots, Videos..). See [artifacts documentation](https://wix.github.io/Detox/docs/api/artifacts).
