name: "⚡️ Enhancement"
description: Suggest an idea for this project
labels: ["type: enhancement ⚡️", "status: triage"]
body:
  - type: markdown
    attributes:
      value: Thanks for taking the time to fill out this enhancement suggestion!
  - type: textarea
    id: idea-description
    attributes:
      label: Describe your idea
      description: "A clear and concise description of what you want to happen.\n
      If your feature request is related to a problem, please describe any other alternative solutions or features you’ve considered."
