name: "🛟 I Need Help - Approach the Maintainers"
description: Ask a general how-to question. We recommend asking for help on Discord / Stack-Overflow, first!
labels: ["user: need help"]
body:
  - type: markdown
    attributes:
      value: If you have issues running Detox or setting it up, please use one of the [bug templates](https://github.com/wix/Detox/issues/new/choose) instead.
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of what you need help with.
    validations:
      required: true
  - type: textarea
    id: environment
    attributes:
      label: Your environment
      description: "Note: the test runner is set in your detox configuration file (e.g. package.json, detox.config)."
      value: "Detox version:
      \nReact Native version:
      \nNode version:
      \nDevice model:
      \nOS:
      \nTest-runner (select one): jest / other"
