name: I Need Help with Detox
description: Ask a general how-to question
title: "[HELP] "
labels: ["user: need help"]
body:
  - type: markdown
    attributes:
      value: If you have issues running Detox or setting it up, please use one of the bug templates instead.
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of what you need help with.
    validations:
      required: true
  - type: markdown
    attributes:
      value: "\n---\n## What is your project environment?"
  - type: input
    id: detox-version
    attributes:
      label: Detox version
  - type: input
    id: rn-version
    attributes:
      label: React Native version
  - type: input
    id: nodejs-version
    attributes:
      label: Node version
  - type: input
    id: device-model
    attributes:
      label: Device model
  - type: input
    id: xcode-version
    attributes:
      label: Xcode version
  - type: input
    id: ios-version
    attributes:
      label: iOS version
  - type: input
    id: macos-version
    attributes:
      label: macOS version
  - type: input
    id: android-version
    attributes:
      label: Android version
  - type: dropdown
    id: test-runner
    attributes:
      label: Test runner
      description: "Note: Test-runner is set in your detox configuration file (e.g. package.json, detox.config)."
      options: ["jest-circus", "jest-jasmine2 (deprecated)", "mocha"]
