/**
 * Acceptance criterion for spec 002.
 *
 * Frozen for implementation: do not edit this file to make it pass. If it seems
 * wrong or impossible, stop and report it rather than weakening it. It speaks
 * only the public dialect: `detox/internals` — never `@detox-remote/*`. The only
 * other import allowed is `./helpers/*`, which is test scaffolding, not product
 * API.
 *
 * The registry has no client API of its own — its entire public surface is the
 * error taxonomy plus behavior, so every test here observes behavior: what a
 * session is told, what `simctl` says afterwards, what a restarted server does.
 *
 * Device models are discovered at runtime, not hardcoded: selection order is
 * unspecified, so the only legal way to pin pool behavior is the
 * single-candidate trick — force the candidate set to one and selection cannot
 * dodge the assertion. A test here never asserts pick order among multiple
 * matches.
 */
import test from 'node:test';
import assert from 'node:assert/strict';

import { init, DetoxErrorCode } from 'detox/internals';
import type { DetoxProgressEvent } from 'detox/internals';

import { startServer } from './helpers/server';
import { assertDetoxError, rejectionOf } from './helpers/errors';
import {
  bootSimulatorExternally,
  deleteSimulatorExternally,
  listDeviceTypeNames,
  listSimulators,
  shutdownSimulatorExternally,
  simulatorState,
  waitUntil,
  type SimulatorListing,
} from './helpers/simctl';

// Not a latency budget: "instant" means the server never queues, sleeps or
// re-polls waiting for a release. In this scenario both clients hold and
// release nothing, so a queueing server would simply never answer — any
// finite ceiling catches that, and this one is set well above the cost of a
// single simctl listing.
const INSTANT_MS = 30_000;

const namesOf = (events: readonly DetoxProgressEvent[]): string[] =>
  events.map((event) => event.name);

interface SingleCandidate {
  readonly model: string;
  readonly udid: string;
}

/** The one capability the reclaim-retry loop needs from a device handle. */
interface Releasable {
  release(): Promise<unknown>;
}

/** A rejection looked at only for its `code` — `assertDetoxError` is for shape. */
interface Coded {
  code?: number;
}

/**
 * Models with exactly one available iPhone/iPad simulator — cold-PINNED, not
 * cold-selected. A filter that skipped any single currently booted would make
 * every caller consume a fresh cold model (one run burned ~7 of them), and a
 * leaner fleet would fail at a precondition assert that read like a product
 * failure. Instead a booted single (usually this run's own leftover) is shut
 * down and waited cold right here, so the same few models serve every caller,
 * run after run. watchOS is excluded: those simulators answer to `simctl` but
 * not to `type: 'ios.simulator'`.
 */
async function shutdownSingles(signal?: AbortSignal): Promise<SingleCandidate[]> {
  const byModel = new Map<string, SimulatorListing[]>();
  for (const sim of await listSimulators(signal)) {
    if (!sim.isAvailable) continue;
    byModel.set(sim.name, [...(byModel.get(sim.name) ?? []), sim]);
  }
  const singles: SingleCandidate[] = [];
  const cooling: SingleCandidate[] = [];
  for (const [model, group] of byModel) {
    if (!/^(iPhone|iPad)/.test(model) || group.length !== 1) continue;
    const single = { model, udid: group[0].udid };
    if (group[0].state !== 'Shutdown') {
      // A device already mid-shutdown only needs the wait below.
      if (group[0].state !== 'Shutting Down') {
        await shutdownSimulatorExternally(single.udid, signal);
      }
      cooling.push(single);
    }
    singles.push(single);
  }
  // The wait is the gate, not the shutdown call: `simctl shutdown` can
  // return while the listing still says `Shutting Down`, and a fixture
  // served lukewarm would flake its caller instead of failing here, loudly.
  for (const single of cooling) {
    await waitUntil(async () => (await simulatorState(single.udid, signal)) === 'Shutdown', {
      signal,
      description: `${single.model} to settle cold before serving as a fixture`,
    });
  }
  return singles;
}

/**
 * Test 1 — instant typed contention.
 *
 * Spec 004 already gates the taxonomy pair across two connections; what it
 * does not gate is that a full pool is refused *instantly* — and that the
 * fail-fast does not decay: three consecutive refusals must each arrive fast.
 * The bound is generous next to the ~10ms answer intended, but it is real:
 * whatever the refusal path does per attempt has to stay off the hot path.
 */
test('contention answers instantly, and stays instant across retries', async (t) => {
  await using server = await startServer({ dedicated: true, maxPool: 1, signal: t.signal });
  await using detox = await init({ server: server.address, signal: t.signal });

  await using held = await detox.allocateDevice({ type: 'ios.simulator' });
  assert.ok(held.info.udid.length > 0);

  for (let attempt = 1; attempt <= 3; attempt += 1) {
    const before = Date.now();
    const err = assertDetoxError(
      await rejectionOf(detox.allocateDevice({ type: 'ios.simulator' }), `retry ${attempt}`),
      `retry ${attempt}`,
    );
    const elapsedMs = Date.now() - before;
    assert.equal(err.code, DetoxErrorCode.DETOX_POOL_EXHAUSTED);
    assert.ok(
      elapsedMs < INSTANT_MS,
      `retry ${attempt}: expected an instant refusal, got one after ${elapsedMs}ms`,
    );
    const holders = err.details?.holders as Array<Record<string, unknown>> | undefined;
    assert.ok(Array.isArray(holders) && holders.length === 1, `retry ${attempt}: expected one holder`);
    assert.equal(holders[0].udid, held.info.udid, `retry ${attempt}: expected the holder named`);
  }

  await held.release();
  await using retry = await detox.allocateDevice({ type: 'ios.simulator' });
  assert.ok(retry.info.udid.length > 0, 'expected the retry after release to succeed');
});

/**
 * Test 2 — terminal no-match, the platform case: an `android` query on a Mac
 * with no emulators must be refused with the terminal code, never answered
 * with an iOS device typed as android. Spec 004 gates the nonexistent-model
 * case; this gates the wrong-platform one.
 */
test('a wrong-platform query is terminal, never a mistyped device', async (t) => {
  await using server = await startServer({ signal: t.signal });
  await using detox = await init({ server: server.address, signal: t.signal });

  const err = assertDetoxError(
    await rejectionOf(
      detox.allocateDevice({ type: 'android.emulator' }),
      'android query on an iOS-only host',
    ),
    'wrong platform',
  );
  assert.equal(err.name, 'NoMatchingDeviceError');
  assert.equal(err.code, DetoxErrorCode.DETOX_NO_MATCHING_DEVICE);
  assert.notEqual(
    err.code,
    DetoxErrorCode.DETOX_POOL_EXHAUSTED,
    'a query nothing on this host can match is terminal, not a capacity problem',
  );
});

/**
 * Test 3 — no orphaned creations. A model with zero simulators forces the
 * create path (the device *type* exists, so the query is creatable — not
 * terminal no-match); the abort lands after `simctl` shows the device exists,
 * so creation demonstrably started. In-memory rollback is enough to pass,
 * deliberately: crash-survival of this cleanup (a persistent create-intent
 * journal) is out of scope for now — the accepted cost of a crash mid-create
 * is one unwanted simulator, never a broken pool.
 */
test('a cancelled creation leaves no half-made simulator behind', async (t) => {
  const existing = new Set((await listSimulators(t.signal)).map((sim) => sim.name));
  const model = (await listDeviceTypeNames(t.signal)).find(
    (name) => name.startsWith('iPhone') && !existing.has(name),
  );
  assert.ok(
    model,
    'precondition: this Mac needs one iPhone device type with no simulator to force the create path',
  );

  await using server = await startServer({ dedicated: true, signal: t.signal });
  await using detox = await init({ server: server.address, signal: t.signal });

  const controller = new AbortController();
  const reason = new Error('spec-002 cancels the creation');
  const allocating = detox.allocateDevice({
    type: 'ios.simulator',
    device: { model },
    signal: controller.signal,
  });
  // Adopted before anything can reject it: a red run must read as an assertion
  // failure, never as an unhandled rejection racing a timeout.
  const rejection = rejectionOf(allocating, 'cancelled creation');

  try {
    await waitUntil(
      async () => (await listSimulators(t.signal)).some((sim) => sim.name === model),
      { signal: t.signal, description: `a ${model} simulator to appear (creation started)` },
    );
    controller.abort(reason);

    const err = assertDetoxError(await rejection, 'cancelled');
    assert.equal(err.name, 'AbortError');

    await waitUntil(
      async () => !(await listSimulators(t.signal)).some((sim) => sim.name === model),
      {
        timeoutMs: 60_000,
        signal: t.signal,
        description: `every half-made ${model} simulator to be deleted`,
      },
    );
  } finally {
    // Cleanup for red runs only — the assertion above has already settled.
    for (const sim of await listSimulators().catch((): SimulatorListing[] => [])) {
      if (sim.name === model) await deleteSimulatorExternally(sim.udid).catch(() => undefined);
    }
  }
});

/**
 * Test 4 — warm reuse. One matching simulator, so selection-unspecified
 * cannot dodge: the second allocation must hand back the same, still-booted
 * device with no boot child operation. The first allocation's boot is asserted
 * too — a warm handoff is only proven warm against a cold start. Warmth is
 * also asserted physically: simctl itself must say the released device kept
 * running, so the skipped boot cannot be a merely suppressed progress event.
 */
test('release keeps the device warm; reallocation skips the boot', async (t) => {
  const single = (await shutdownSingles(t.signal))[0];
  assert.ok(single, 'precondition: a shut-down model with exactly one simulator');

  await using server = await startServer({ signal: t.signal });
  await using detox = await init({ server: server.address, signal: t.signal });

  const onFirst = t.mock.fn((_event: DetoxProgressEvent): void => {});
  const first = await detox.allocateDevice({
    type: 'ios.simulator',
    device: { model: single.model },
    onProgress: onFirst,
  });
  assert.equal(first.info.udid, single.udid);
  assert.ok(
    namesOf(onFirst.mock.calls.map(({ arguments: [event] }) => event)).includes('boot'),
    'sanity: the first allocation of a shut-down device must boot it',
  );
  await first.release();
  assert.equal(
    await simulatorState(single.udid, t.signal),
    'Booted',
    'warmth is physical: simctl must say the released device kept running',
  );

  const onSecond = t.mock.fn((_event: DetoxProgressEvent): void => {});
  await using second = await detox.allocateDevice({
    type: 'ios.simulator',
    device: { model: single.model },
    onProgress: onSecond,
  });
  assert.equal(second.info.udid, single.udid, 'single candidate: the same device comes back');
  assert.equal(second.state, 'booted', 'expected a ready device without a second boot');
  assert.ok(
    !namesOf(onSecond.mock.calls.map(({ arguments: [event] }) => event)).includes('boot'),
    'expected no boot child operation on a warm handoff',
  );
});

/**
 * Test 5 — eviction under pressure, scope respected. Two warm released
 * devices fill the cap; an allocation for a third model needs a fresh slot, so
 * the least recently used warm device is shut down — and only it. The device
 * booted behind the server's back before it started (found-booted, never
 * touched) must not be evicted, and must not eat pool capacity either.
 */
test('eviction takes the least recently used warm device, never a foreign boot', async (t) => {
  const singles = await shutdownSingles(t.signal);
  assert.ok(singles.length >= 4, 'precondition: four idle single-simulator models');
  const [foreign, older, newer, incoming] = singles;

  // Foreign boot before the server's first breath: a previous life's leftover.
  await bootSimulatorExternally(foreign.udid, t.signal);
  try {
    await using server = await startServer({ dedicated: true, maxPool: 2, signal: t.signal });
    await using detox = await init({ server: server.address, signal: t.signal });

    const first = await detox.allocateDevice({ type: 'ios.simulator', device: { model: older.model } });
    assert.equal(first.info.udid, older.udid);
    await first.release();

    const second = await detox.allocateDevice({ type: 'ios.simulator', device: { model: newer.model } });
    assert.equal(second.info.udid, newer.udid);
    await second.release();

    // Cap reached by two warm devices; this one needs a fresh slot.
    await using third = await detox.allocateDevice({
      type: 'ios.simulator',
      device: { model: incoming.model },
    });
    assert.equal(third.state, 'booted');

    await waitUntil(
      async () => (await simulatorState(older.udid, t.signal)) !== 'Booted',
      { signal: t.signal, description: 'the LRU warm device to be shut down (evicted)' },
    );
    assert.equal(
      await simulatorState(newer.udid, t.signal),
      'Booted',
      'one slot was needed; the fresher warm device stays warm',
    );
    assert.equal(
      await simulatorState(foreign.udid, t.signal),
      'Booted',
      'a found-booted device is not evictable until first touched',
    );
  } finally {
    await shutdownSimulatorExternally(foreign.udid).catch(() => undefined);
  }
});

/**
 * Test 6 — restart parity. The server dies holding an allocation; the next
 * life trusts nothing but the live listing: `_busy` starts empty, so the very
 * same simulator is allocatable at once — and the only startup ceremony is one
 * inventory line, exactly once.
 */
test('a restarted server trusts the live listing and says so once', async (t) => {
  const single = (await shutdownSingles(t.signal))[0];
  assert.ok(single, 'precondition: a shut-down model with exactly one simulator');

  const firstLife = await startServer({ dedicated: true, signal: t.signal });
  const casualty = await init({ server: firstLife.address, signal: t.signal });
  try {
    const device = await casualty.allocateDevice({
      type: 'ios.simulator',
      device: { model: single.model },
    });
    assert.equal(device.info.udid, single.udid);
    assert.equal(device.state, 'booted');
  } finally {
    // Down with the allocation still held — SIGTERM here, but the contract
    // is the same for any exit: the next life owes nothing to this one.
    await firstLife.stop();
    await Promise.resolve(casualty[Symbol.asyncDispose]()).catch(() => undefined);
  }

  await using secondLife = await startServer({ dedicated: true, signal: t.signal });
  await using detox = await init({ server: secondLife.address, signal: t.signal });

  await using again = await detox.allocateDevice({
    type: 'ios.simulator',
    device: { deviceId: single.udid },
  });
  assert.equal(again.info.udid, single.udid, 'the first life\'s device is allocatable at once');
  assert.equal(again.state, 'booted');

  // The format is the contract: this line is what a human greps after an
  // incident, and "0 owned" is the no-persistence rule stated as output.
  const inventoryLines = (): number =>
    (secondLife.logs().match(/\d+ booted, 0 owned, \d+ half-made deleted/g) ?? []).length;
  await waitUntil(() => inventoryLines() >= 1, {
    signal: t.signal,
    description: 'the startup inventory line to be logged',
  });
  // Let a few reconcile ticks pass first: "exactly once" must survive a loop
  // that would otherwise re-log the line every tick. The line must go to
  // stdout — the helper keeps stdout whole but only a tail of stderr.
  await new Promise((resolve) => setTimeout(resolve, 2_500));
  assert.equal(inventoryLines(), 1, 'expected the inventory line exactly once per server life');
});

/**
 * Test 7 — multi-device. Two concurrent allocations in one session,
 * independent handles, and a disconnect that reclaims what was never
 * released. The verifier retries per the fail-fast norm: reclaim runs
 * detached, so the slots may take a beat to come back — but they must come
 * back without anyone releasing anything. Much of this held against the
 * pre-registry server on purpose: it is behavior the registry rewrite must
 * not lose, so this test is a regression guard as much as a gate.
 */
test('one session holds two devices; disconnect reclaims what release did not', async (t) => {
  await using server = await startServer({ dedicated: true, maxPool: 2, signal: t.signal });
  const session = await init({ server: server.address, signal: t.signal });
  try {
    const [left, right] = await Promise.all([
      session.allocateDevice({ type: 'ios.simulator' }),
      session.allocateDevice({ type: 'ios.simulator' }),
    ]);
    assert.notEqual(left.info.udid, right.info.udid, 'two allocations, two devices');
    assert.notEqual(left.info.allocationId, right.info.allocationId);

    // Handles are independent: cycling one must not touch its sibling.
    await left.shutdown();
    assert.equal(left.state, 'shutdown');
    assert.equal(right.state, 'booted', 'the sibling handle must be unaffected');

    await left.release();
    await right.boot(); // idempotent: proves the handle outlives its sibling's release
    // waitUntil, not a bare assert: `device.state` has two client-side writers
    // (a poll can transiently overwrite the response) — that race is not this
    // test's concern to reproduce.
    await waitUntil(() => right.state === 'booted', {
      signal: t.signal,
      description: "the sibling's state to settle at booted",
    });
    // `right` is deliberately NOT released: disconnect must reclaim it.
  } finally {
    await session.disconnect();
  }

  await using verifier = await init({ server: server.address, signal: t.signal });
  const reclaimed: Releasable[] = [];
  await waitUntil(
    async () => {
      // Release-before-retry, the ecosystem idiom, scripted.
      try {
        const first = await verifier.allocateDevice({ type: 'ios.simulator' });
        reclaimed.push(first);
        const second = await verifier.allocateDevice({ type: 'ios.simulator' });
        reclaimed.push(second);
        return true;
      } catch (error) {
        if ((error as Coded).code !== DetoxErrorCode.DETOX_POOL_EXHAUSTED) throw error;
        await Promise.all(reclaimed.splice(0).map((device) => device.release()));
        return false;
      }
    },
    { signal: t.signal, description: 'both slots to be reclaimed after disconnect' },
  );
  await Promise.all(reclaimed.map((device) => device.release()));
});

/**
 * Test 8 — the wire-visible half of owner-checked release: a duplicate
 * release from a handle whose device has moved on frees nothing. What the
 * stale call itself returns is deliberately unpinned (error or quiet no-op);
 * theft is the one forbidden outcome. The nastier theft vector — a stale
 * *rollback* freeing by bare udid after a reclaim — is not deterministically
 * reachable through the public dialect and is covered at unit level.
 */
test('a duplicate release frees nothing once the device has moved on', async (t) => {
  await using server = await startServer({ dedicated: true, maxPool: 1, signal: t.signal });
  await using clientA = await init({ server: server.address, signal: t.signal });
  await using clientB = await init({ server: server.address, signal: t.signal });

  const first = await clientA.allocateDevice({ type: 'ios.simulator' });
  await first.release();
  await using second = await clientB.allocateDevice({ type: 'ios.simulator' });

  // The duplicate release, against a device clientB now holds.
  await Promise.resolve(first.release()).catch(() => undefined);

  const err = assertDetoxError(
    await rejectionOf(
      clientA.allocateDevice({ type: 'ios.simulator' }),
      'allocation after the stale release',
    ),
    'still held',
  );
  assert.equal(err.code, DetoxErrorCode.DETOX_POOL_EXHAUSTED, 'the slot must still be taken');
  const holders = err.details?.holders as Array<Record<string, unknown>> | undefined;
  assert.ok(Array.isArray(holders) && holders.length === 1);
  assert.equal(
    holders[0].allocationId,
    second.info.allocationId,
    'the holder must still be the new owner — the stale release freed nothing',
  );
  assert.equal(second.state, 'booted', 'the new owner\'s device must be untouched');
});

/**
 * The registry is the only address book. A request carried by a released
 * handle is answered with a typed stale-handle error — never a guess, and
 * never a touch on the device's next owner. The single-candidate trick pins
 * the handoff, so "the next owner holds the very device the dead handle used
 * to name" is a fact, not a probability. `boot` already routes owner-checked;
 * the invariant is pinned here so the device-action surface (launchApp and
 * friends, spec 003) must inherit it.
 */
test('a released handle is a stale address, never a route to the next owner', async (t) => {
  const single = (await shutdownSingles(t.signal))[0];
  assert.ok(single, 'precondition: a shut-down model with exactly one simulator');

  await using server = await startServer({ signal: t.signal });
  await using detox = await init({ server: server.address, signal: t.signal });

  const first = await detox.allocateDevice({
    type: 'ios.simulator',
    device: { model: single.model },
  });
  assert.equal(first.info.udid, single.udid);
  await first.release();

  // The same device moves on to its next owner…
  await using second = await detox.allocateDevice({
    type: 'ios.simulator',
    device: { model: single.model },
  });
  assert.equal(second.info.udid, single.udid, 'single candidate: the same device comes back');

  // …and the dead handle can no longer reach it.
  const err = assertDetoxError(
    await rejectionOf(first.boot(), 'boot on a released handle'),
    'a released handle must answer with a typed error',
  );
  assert.equal(err.code, DetoxErrorCode.DETOX_STALE_HANDLE);
  assert.equal(
    await simulatorState(single.udid, t.signal),
    'Booted',
    'the refused call must not have touched the next owner',
  );
  assert.equal(second.state, 'booted', 'the sibling handle must be unaffected');
});

/**
 * Test 9 — the multi-device drain. Two clients each hold one device on a
 * two-slot server and want a second: both refusals are instant and name BOTH
 * holders across connections; then the documented idiom — release ALL, back
 * off, re-acquire the full set — drains the standoff. The test scripts the
 * turns that jitter randomizes in the wild, which is what makes the drain
 * deterministic here.
 *
 * Holder ids are asserted as opaque values, never dereferenced: `ageMs` is the
 * hold age of the allocation, and actionability of `allocationId` is a known
 * gap this spec's registry closes separately.
 */
test('two greedy clients drain instead of livelocking', async (t) => {
  await using server = await startServer({ dedicated: true, maxPool: 2, signal: t.signal });
  await using alice = await init({ server: server.address, signal: t.signal });
  await using bob = await init({ server: server.address, signal: t.signal });

  const aliceHolds = await alice.allocateDevice({ type: 'ios.simulator' });
  const bobHolds = await bob.allocateDevice({ type: 'ios.simulator' });
  const heldUdids = new Set([aliceHolds.info.udid, bobHolds.info.udid]);
  assert.equal(heldUdids.size, 2);

  for (const [who, session] of [['alice', alice], ['bob', bob]] as const) {
    const before = Date.now();
    const err = assertDetoxError(
      await rejectionOf(session.allocateDevice({ type: 'ios.simulator' }), `${who}'s second ask`),
      `${who}'s refusal`,
    );
    const elapsedMs = Date.now() - before;
    assert.equal(err.code, DetoxErrorCode.DETOX_POOL_EXHAUSTED);
    assert.ok(elapsedMs < INSTANT_MS, `${who}: expected an instant refusal, got ${elapsedMs}ms`);

    const holders = err.details?.holders as Array<Record<string, unknown>> | undefined;
    assert.ok(Array.isArray(holders) && holders.length === 2, `${who}: expected both holders named`);
    assert.deepEqual(
      new Set(holders.map((holder) => holder.udid)),
      heldUdids,
      `${who}: expected the holders to name both held devices, across connections`,
    );
    for (const holder of holders) {
      assert.equal(typeof holder.allocationId, 'string', `${who}: opaque allocation id`);
      assert.ok(typeof holder.ageMs === 'number' && holder.ageMs >= 0, `${who}: hold age`);
    }
  }

  // The idiom, scripted: everyone releases everything…
  await aliceHolds.release();
  await bobHolds.release();

  // …then alice takes her full set and completes…
  const alicePair = await Promise.all([
    alice.allocateDevice({ type: 'ios.simulator' }),
    alice.allocateDevice({ type: 'ios.simulator' }),
  ]);
  assert.notEqual(alicePair[0].info.udid, alicePair[1].info.udid);
  await Promise.all(alicePair.map((device) => device.release()));

  // …and bob takes his. Drained: both clients finished, nobody waited on a queue.
  const bobPair = await Promise.all([
    bob.allocateDevice({ type: 'ios.simulator' }),
    bob.allocateDevice({ type: 'ios.simulator' }),
  ]);
  assert.notEqual(bobPair[0].info.udid, bobPair[1].info.udid);
  await Promise.all(bobPair.map((device) => device.release()));
});
