-dontwarn org.xmlpull.**
-dontwarn sun.misc.**

-dontnote android.**
-dontnote androidx.**
-dontnote java.**
-dontnote javax.**
-dontnote kotlin.**
-dontnote org.apache.**
-dontnote junit.**
-dontnote org.junit.**
-dontnote org.joor.**
-dontnote org.hamcrest.**
-dontnote com.facebook.**
