  - label: ":android::detox: RN .73 + Android: Tests app"
    command:
      - "nvm install"
      - "./scripts/ci.android.sh"
    env:
      REACT_NATIVE_VERSION: 0.73.2
      DETOX_DISABLE_POD_INSTALL: true
      DETOX_DISABLE_POSTINSTALL: true
      JAVA_HOME: /opt/openjdk/jdk-17.0.9.jdk/Contents/Home/
    artifact_paths:
      - "/Users/builder/work/coverage/**/*.lcov"
      - "/Users/builder/work/**/allure-report-*.html"
      - "/Users/builder/work/artifacts*.tar.gz"
