  - label: ":android::react: RN .78 + Android: Demo app"
    command:
      - "nvm install"
      - "./scripts/demo-projects.android.sh"
    env:
      REACT_NATIVE_VERSION: 0.78.2
      DETOX_DISABLE_POD_INSTALL: true
      DETOX_DISABLE_POSTINSTALL: true
    artifact_paths:
      - "/Users/builder/uibuilder/work/coverage/**/*.lcov"
      - "/Users/builder/uibuilder/work/artifacts*.tar.gz"
