  - label: ":ios::detox: RN .71 + iOS: Tests app"
    command:
      - "nvm install"
      - "./scripts/ci.ios.sh"
    env:
      REACT_NATIVE_VERSION: 0.71.10
      JAVA_HOME: /opt/openjdk/jdk-17.0.9.jdk/Contents/Home/
    artifact_paths:
      - "/Users/builder/work/coverage/**/*.lcov"
      - "/Users/builder/work/**/allure-report-*.html"
      - "/Users/builder/work/artifacts*.tar.gz"
