  - label: ":android::react: RN .71 + Android: Demo app"
    command:
      - "nvm install"
      - "./scripts/demo-projects.android.sh"
    env:
      REACT_NATIVE_VERSION: 0.71.10
      DETOX_DISABLE_POD_INSTALL: true
      DETOX_DISABLE_POSTINSTALL: true
      JAVA_HOME: /opt/openjdk/jdk-17.0.9.jdk/Contents/Home/
    artifact_paths:
      - "/Users/builder/work/coverage/**/*.lcov"
      - "/Users/builder/work/artifacts*.tar.gz"
