  - label: ":android::detox: RN .71 + Android: Tests app"
    command:
      - "nvm install"
      - "./scripts/ci.android.sh"
    env:
      REACT_NATIVE_VERSION: 0.71.10
      DETOX_DISABLE_POD_INSTALL: true
      DETOX_DISABLE_POSTINSTALL: true
      SKIP_UNIT_TESTS: true
      # JAVA_HOME: /opt/openjdk/openlogic-openjdk-17.0.9+9-mac-x64/jdk-17.0.9.jdk/Contents/Home
    artifact_paths:
      - "/Users/builder/work/coverage/**/*.lcov"
      - "/Users/builder/work/**/allure-report-*.html"
      - "/Users/builder/work/artifacts*.tar.gz"
    agents:
      queue: m2-oss
