  - label: ":android::react: RN .76 + Android: Demo app"
    command:
      - "nvm install"
      - "./scripts/demo-projects.android.sh"
    env:
      REACT_NATIVE_VERSION: 0.76.3
      REACT_NATIVE_COMPAT_TEST: true # Only set 'true' in jobs with the latest supported RN
      DETOX_DISABLE_POD_INSTALL: true
      DETOX_DISABLE_POSTINSTALL: true
    artifact_paths:
      - "/Users/builder/uibuilder/work/coverage/**/*.lcov"
      - "/Users/builder/uibuilder/work/artifacts*.tar.gz"
