  - label: ":android::detox: RN .70 + Android: Tests app"
    command:
      - "nvm install"
    env:
      REACT_NATIVE_VERSION: 0.70.7
      DETOX_DISABLE_POD_INSTALL: true
      DETOX_DISABLE_POSTINSTALL: true
      SKIP_UNIT_TESTS: true
    artifact_paths:
      - "/Users/builder/work/coverage/**/*.lcov"
      - "/Users/builder/work/**/allure-report-*.html"
      - "/Users/builder/work/artifacts*.tar.gz"
