  - label: ":android::react: RN.66 + Android: Demo app"
    command:
      - "nvm install"
      - "JAVA_HOME=/usr/local/opt/openjdk@11/ ./scripts/demo-projects.android.sh"
    env:
      REACT_NATIVE_VERSION: 0.66.4
      REACT_NATIVE_COMPAT_TEST: true
      DETOX_DISABLE_POD_INSTALL: true
      DETOX_DISABLE_POSTINSTALL: true
    artifact_paths:
      - "/Users/builder/work/coverage/**/*.lcov"
      - "/Users/builder/work/artifacts*.tar.gz"
