  - label: ":android::detox: RN .83 + Android: Tests app"
    command:
      - "nvm install"
      - "./scripts/ci.android.sh"
    env:
      REACT_NATIVE_VERSION: 0.83.0
      RCT_NEW_ARCH_ENABLED: 1
      TEST_GENYCLOUD_SANITY: true
      DETOX_DISABLE_POD_INSTALL: true
      DETOX_DISABLE_POSTINSTALL: true
    artifact_paths:
      - "/Users/builder/uibuilder/work/coverage/**/*.lcov"
      - "/Users/builder/uibuilder/work/**/allure-report-*.html"
      - "/Users/builder/uibuilder/work/artifacts*.tar.gz"

