  - label: ":android::detox: RN.69 + Android: Tests app"
    command:
      - "nvm install"
      - "./scripts/ci.android.sh"
    env:
      REACT_NATIVE_VERSION: 0.69.7
      DETOX_DISABLE_POD_INSTALL: true
      DETOX_DISABLE_POSTINSTALL: true
      SKIP_UNIT_TESTS: true
    artifact_paths:
      - "/Users/builder/work/coverage/**/*.lcov"
      - "/Users/builder/work/allure*.tar.gz"
      - "/Users/builder/work/artifacts*.tar.gz"
